DROP TABLE Imposer;
DROP TABLE Quotter;
DROP TABLE Relevé;
DROP TABLE COMPTEUR;
DROP TABLE ARCHIVAGE_LOUER; 
DROP TABLE LOUER;
DROP TABLE FACTURE;
DROP TABLE ARCHIVAGE_FACTURE;
DROP TABLE DIAGNOSTIC;
DROP TABLE BIEN;
DROP TABLE IMPOT;
DROP TABLE QUOTITE;
DROP TABLE ICC;
DROP TABLE ECHEANCE;
DROP TABLE ASSURANCE;
DROP TABLE ENTREPRISE;
DROP TABLE IMMEUBLE;
DROP TABLE LOCATAIRE;
DROP TABLE Archivage_Locataire;

DROP SEQUENCE compteur_Diagnostic;
DROP SEQUENCE compteur_Impot;

DROP TABLE BIEN;
DROP TABLE IMMEUBLE;

